### PR TITLE
add robo-diffusion

### PR DESCRIPTION
**Pull request by nousr**
<p align="center"> 

<h3 align="center"> this pr will add support for the robo-diffusion model </h3>
<div align="center">
<a href="https://huggingface.co/nousr/robo-diffusion/blob/main/models/robo-diffusion-v1.ckpt">model checkpoint</a>
</div>

### CODE REVIEW

**Comment by nousr** [comment]
let me know how you feel about the auto download 

also, btw, you can download the checkpoints that require authentication over the web using the following format

`https://$HF_USERNAME:$API_TOKEN@huggingface.co/user/model`

(if you wanted to extend functionality to all checkpoints)

**Comment by kabachuha** [comment]
Why limit it just with robo-diffusion? I think many are longing for download Waifu-diffusion the same way

**Comment by kabachuha** [comment]
Very well, so let's merge it and then I or somebody else would add WD link

**Comment by nousr** [comment]
alright i'll take this out of draft, but someone should test it and verify it works for them as well

**Comment by nousr** [comment]
Okay I added authentication ability for the original stable diffusion models

it will error out if they didn't accept the terms (like so)

image

**Pull request merged**
